### ISSUE TITLE
zero.rs is deprecated

### ISSUE THREAD

**Issue by ghost** [Arcterus/kRnel#1]
From [zero.rs](https://github.com/pcwalton/zero.rs):

> This is deprecated and is no longer maintained. It is no longer necessary to use this to
> achieve runtime-less operation; just use #[start] and/or #[no_std] and avoid the runtime.

So, does kRnel really need zero.rs?
I'm a poor newbie, sorry in advance if that is a stupid question. Thank you!

**Comment by Arcterus** [comment]
It works without the runtime, but currently some of the traits and functions within zero.rs are being used. However, I'm hoping to eventually move the zero.rs stuff into sensible files, rather than the way it is right now with most of the rudimentary things in one giant file.

So, yes, zero.rs is needed for the time being.
